/**
 * Image generation using Google's Gemini 3 Pro Image API
 */
import { getClient } from "@/lib/gemini";

interface ImageGenerationOptions {
  prompt: string;
  negativePrompt?: string;
  numberOfImages?: number;
  aspectRatio?: "1:1" | "16:9" | "9:16" | "4:3" | "3:4" | "5:4";
  safetySetting?: "block_most" | "block_some" | "block_few" | "block_none";
  imageSize?: "1K" | "2K" | "4K";
}

/**
 * Generate an image using Google's Gemini 3 Pro Image API
 * @param options - Image generation options
 * @returns Base64 encoded image data
 */
export async function generateImageWithImagen(
  options: ImageGenerationOptions
): Promise<string> {
  const client = getClient();

  const {
    prompt,
    negativePrompt,
    aspectRatio = "16:9",
    imageSize = "2K",
  } = options;

  // Build the prompt with negative prompt if provided
  const fullPrompt = negativePrompt
    ? `${prompt}\n\nAvoid: ${negativePrompt}`
    : prompt;

  console.log(`🎨 Starting image generation...`);
  console.log(`   Model: gemini-3-pro-image-preview`);
  console.log(`   Aspect Ratio: ${aspectRatio}`);
  console.log(`   Resolution: ${imageSize}`);
  console.log(`   Prompt: ${prompt.substring(0, 150)}${prompt.length > 150 ? '...' : ''}`);

  const startTime = Date.now();

  const response = await client.models.generateContent({
    model: "gemini-3-pro-image-preview",
    contents: fullPrompt,
    config: {
      responseModalities: ["TEXT", "IMAGE"],
      imageConfig: {
        aspectRatio,
        imageSize,
      },
    },
  });

  if (!response.candidates || response.candidates.length === 0) {
    throw new Error("No images generated by Gemini 3 Pro Image API");
  }

  const candidate = response.candidates[0];
  if (!candidate.content || !candidate.content.parts) {
    throw new Error("Invalid response structure from Gemini 3 Pro Image API");
  }

  // Find the image part in the response
  const imagePart = candidate.content.parts.find(
    (part: any) => part.inlineData
  );

  if (!imagePart || !imagePart.inlineData?.data) {
    throw new Error("No image data generated by Gemini 3 Pro Image API");
  }

  const duration = ((Date.now() - startTime) / 1000).toFixed(2);
  console.log(`✅ Image generation completed in ${duration}s`);

  return imagePart.inlineData.data;
}

/**
 * Save base64 image to a file in the public directory
 * @param base64Data - Base64 encoded image data
 * @param filename - Filename to save as (without extension)
 * @returns Public URL path to the saved image
 */
export async function saveImageToPublic(
  base64Data: string,
  filename: string
): Promise<string> {
  const fs = await import("fs/promises");
  const path = await import("path");

  // Decode base64 to buffer
  const buffer = Buffer.from(base64Data, "base64");

  // Save to public directory
  const publicDir = path.join(process.cwd(), "public", "generated");

  // Create directory if it doesn't exist
  try {
    await fs.mkdir(publicDir, { recursive: true });
  } catch (error) {
    // Directory might already exist
  }

  const filepath = path.join(publicDir, `${filename}.png`);
  await fs.writeFile(filepath, buffer);

  // Return public URL
  return `/generated/${filename}.png`;
}

/**
 * Generate image and save it to public directory
 * @param prompt - Image generation prompt
 * @param filename - Filename to save as
 * @param aspectRatio - Image aspect ratio
 * @param imageSize - Image resolution (1K, 2K, or 4K)
 * @returns Public URL path to the saved image
 */
export async function generateAndSaveImage(
  prompt: string,
  filename: string,
  aspectRatio: "1:1" | "16:9" | "9:16" | "4:3" | "3:4" | "5:4" = "16:9",
  imageSize: "1K" | "2K" | "4K" = "2K"
): Promise<string> {
  console.log(`🎨 Generating image: ${filename}`);
  console.log(`   Prompt: ${prompt.substring(0, 100)}...`);

  const base64Image = await generateImageWithImagen({
    prompt,
    aspectRatio,
    imageSize,
  });

  const publicUrl = await saveImageToPublic(base64Image, filename);

  console.log(`✅ Image saved: ${publicUrl}`);

  return publicUrl;
}
