/**
 * Image generation using Google's Imagen API (Nano Banana Pro)
 */

interface ImageGenerationOptions {
  prompt: string;
  negativePrompt?: string;
  numberOfImages?: number;
  aspectRatio?: "1:1" | "16:9" | "9:16" | "4:3" | "3:4";
  safetySetting?: "block_most" | "block_some" | "block_few" | "block_none";
}

/**
 * Generate an image using Google's Imagen API
 * @param options - Image generation options
 * @returns Base64 encoded image data
 */
export async function generateImageWithImagen(
  options: ImageGenerationOptions
): Promise<string> {
  const apiKey = process.env.GOOGLE_API_KEY;
  if (!apiKey) {
    throw new Error("GOOGLE_API_KEY environment variable is not set");
  }

  const {
    prompt,
    negativePrompt = "blurry, low quality, distorted, disfigured",
    numberOfImages = 1,
    aspectRatio = "16:9",
  } = options;

  // Try Imagen 3 endpoint
  const url = `https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-001:generateImages`;

  const requestBody = {
    prompt,
    negativePrompt,
    numberOfImages,
    aspectRatio,
  };

  const response = await fetch(`${url}?key=${apiKey}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(requestBody),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(
      `Imagen API request failed: ${response.status} ${response.statusText} - ${errorText}`
    );
  }

  const data = await response.json();

  if (!data.images || data.images.length === 0) {
    throw new Error("No images generated by Imagen API");
  }

  // Return the first generated image as base64
  const imageData = data.images[0].bytesBase64Encoded;
  return imageData;
}

/**
 * Save base64 image to a file in the public directory
 * @param base64Data - Base64 encoded image data
 * @param filename - Filename to save as (without extension)
 * @returns Public URL path to the saved image
 */
export async function saveImageToPublic(
  base64Data: string,
  filename: string
): Promise<string> {
  const fs = await import("fs/promises");
  const path = await import("path");

  // Decode base64 to buffer
  const buffer = Buffer.from(base64Data, "base64");

  // Save to public directory
  const publicDir = path.join(process.cwd(), "public", "generated");

  // Create directory if it doesn't exist
  try {
    await fs.mkdir(publicDir, { recursive: true });
  } catch (error) {
    // Directory might already exist
  }

  const filepath = path.join(publicDir, `${filename}.png`);
  await fs.writeFile(filepath, buffer);

  // Return public URL
  return `/generated/${filename}.png`;
}

/**
 * Generate image and save it to public directory
 * @param prompt - Image generation prompt
 * @param filename - Filename to save as
 * @param aspectRatio - Image aspect ratio
 * @returns Public URL path to the saved image
 */
export async function generateAndSaveImage(
  prompt: string,
  filename: string,
  aspectRatio: "1:1" | "16:9" | "9:16" | "4:3" | "3:4" = "16:9"
): Promise<string> {
  console.log(`🎨 Generating image: ${filename}`);
  console.log(`   Prompt: ${prompt.substring(0, 100)}...`);

  const base64Image = await generateImageWithImagen({
    prompt,
    aspectRatio,
  });

  const publicUrl = await saveImageToPublic(base64Image, filename);

  console.log(`✅ Image saved: ${publicUrl}`);

  return publicUrl;
}
